/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BaseAsyncSelect: typeof import("./src/components/base/BaseAsyncSelect.vue")["default"];
    BaseButton: typeof import("./src/components/base/BaseButton.vue")["default"];
    BaseCollapseItem: typeof import("./src/components/base/BaseCollapseItem.vue")["default"];
    BaseDialog: typeof import("./src/components/base/BaseDialog.vue")["default"];
    BaseDrawer: typeof import("./src/components/base/BaseDrawer.vue")["default"];
    BaseEmpty: typeof import("./src/components/base/BaseEmpty.vue")["default"];
    BaseForm: typeof import("./src/components/base/BaseForm.vue")["default"];
    BaseIframe: typeof import("./src/components/base/BaseIframe.vue")["default"];
    BaseImg: typeof import("./src/components/base/BaseImg.vue")["default"];
    BaseInput: typeof import("./src/components/base/BaseInput.vue")["default"];
    BasePagination: typeof import("./src/components/base/BasePagination.vue")["default"];
    BaseSearchFilter: typeof import("./src/components/base/BaseSearchFilter/index.vue")["default"];
    BaseSelect: typeof import("./src/components/base/BaseSelect.vue")["default"];
    BaseSvg: typeof import("./src/components/base/BaseSvg.vue")["default"];
    BaseTable: typeof import("./src/components/base/BaseTable/index.vue")["default"];
    BaseTooltip: typeof import("./src/components/base/BaseTooltip.vue")["default"];
    BeyondTooltip: typeof import("./src/components/BeyondTooltip.vue")["default"];
    ContextMenuPanel: typeof import("./src/components/ContextMenuPanel.vue")["default"];
    DeleteTipDialog: typeof import("./src/components/DeleteTipDialog.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSelectV2: typeof import("element-plus/es")["ElSelectV2"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    IconFont: typeof import("./src/components/IconFont.vue")["default"];
    MainHeader: typeof import("./src/components/base/MainHeader.vue")["default"];
    RadioTabs: typeof import("./src/components/RadioTabs.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
